export const FETCH_NEW_ARRIVAL_PRODUCT_START = 'FETCH_NEW_ARRIVAL_START';
export const FETCH_NEW_ARRIVAL_SUCCESS ='FETCH_NEW_ARRIVAL_SUCCESS';
export const FETCH_NEW_ARRIVAL_FAILURE = 'FETCH_NEW_ARRIVAL_FAILURE';