export const FETCH_FEATURED_PRODUCT_START = 'FETCH_FEATURED_PRODUCT_START';
export const FETCH_FEATURED_PRODUCT_SUCCESS ='FETCH_FEATURED_PRODUCT_SUCCESS';
export const FETCH_FEATURED_PRODUCT_FAILURE = 'FETCH_FEATURED_PRODUCT_FAILURE';